services:
  app_proxy:
    environment:
      APP_HOST: tm-traefik-manager-agent_agent_1
      APP_PORT: 8090
      PROXY_AUTH_ADD: "false"

  agent:
    image: ghcr.io/chr0nzz/traefik-manager-agent:latest
    restart: on-failure
    environment:
      TRAEFIK_API_URL: http://tm-traefik-manager-agent_traefik_1:8080
      CONFIG_PATH: /app/dynamic
      STATIC_CONFIG_PATH: /app/static/traefik.yml
      ACME_JSON_PATH: /app/acme/acme.json
      ACCESS_LOG_PATH: /app/logs/access.log
      RESTART_METHOD: poison-pill
      SIGNAL_FILE_PATH: /signals/restart.sig
      BACKUP_DIR: /app/backups
    volumes:
      - ${APP_DATA_DIR}/data/agent/backups:/app/backups
      - ${APP_DATA_DIR}/data/traefik/dynamic:/app/dynamic
      - ${APP_DATA_DIR}/data/traefik/static:/app/static
      - ${APP_DATA_DIR}/data/traefik/acme:/app/acme
      - ${APP_DATA_DIR}/data/traefik/logs:/app/logs:ro
      - ${APP_DATA_DIR}/data/signals:/signals

  traefik:
    image: traefik:latest
    restart: unless-stopped
    command: --configFile=/etc/traefik/static/traefik.yml
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 43080:80
      - 43443:443
    healthcheck:
      test: ["CMD-SHELL", "[ ! -f /signals/restart.sig ] || (rm /signals/restart.sig && kill -TERM 1)"]
      interval: 5s
      timeout: 3s
      retries: 1
    volumes:
      - ${APP_DATA_DIR}/data/traefik/static:/etc/traefik/static:ro
      - ${APP_DATA_DIR}/data/traefik/dynamic:/etc/traefik/dynamic:ro
      - ${APP_DATA_DIR}/data/traefik/acme:/etc/traefik/acme
      - ${APP_DATA_DIR}/data/traefik/logs:/var/log/traefik
      - ${APP_DATA_DIR}/data/signals:/signals
